# Generated by Django 4.1.5 on 2023-01-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('end_date', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('OS', 'Volunteer'), ('IS', 'Internship'), ('PT', 'Part Time'), ('FT', 'Full Time'), ('RS', 'Research')], default='IS', max_length=2)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='def-favicon.ico', upload_to='')),
                ('previous_logo', models.TextField(blank=True)),
                ('intro', models.BooleanField(default=True)),
                ('intro_background', models.ImageField(default='def-intro-back.jpg', upload_to='backgrounds')),
                ('previous_intro_background', models.TextField(blank=True)),
                ('work', models.BooleanField(default=True)),
                ('work_background', models.ImageField(default='def-work-back.jpg', upload_to='backgrounds')),
                ('previous_work_background', models.TextField(blank=True)),
                ('experience', models.BooleanField(default=True)),
                ('experience_background', models.ImageField(default='def-experience-back.jpg', upload_to='backgrounds')),
                ('previous_experience_background', models.TextField(blank=True)),
                ('about', models.BooleanField(default=True)),
                ('about_background', models.ImageField(default='def-about-back.jpg', upload_to='backgrounds')),
                ('previous_about_background', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'HomePage',
                'verbose_name_plural': 'HomePages',
            },
        ),
        migrations.CreateModel(
            name='MyIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_text', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=200)),
                ('major', models.CharField(blank=True, max_length=50)),
                ('minor', models.CharField(blank=True, max_length=50)),
                ('micro_credential', models.CharField(blank=True, max_length=50)),
                ('picture', models.ImageField(default='default-me-pic.png', upload_to='')),
                ('previous_picture', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('resume_link', models.TextField(blank=True, default='#')),
            ],
            options={
                'verbose_name': 'My Intro',
                'verbose_name_plural': 'My Intros',
            },
        ),
        migrations.CreateModel(
            name='SocialWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50)),
                ('classes', models.TextField()),
                ('link', models.TextField()),
            ],
            options={
                'verbose_name': 'Social Website',
                'verbose_name_plural': 'Social Websites',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('OS', 'Open Source'), ('PR', 'Project'), ('CB', 'Contribution')], default='PR', max_length=2)),
                ('description', models.TextField(blank=True)),
                ('show_status', models.BooleanField(default=True)),
                ('status_message', models.TextField(blank=True, default='In development.')),
                ('in_production', models.BooleanField(default=False)),
                ('production_link', models.TextField(blank=True)),
                ('on_github', models.BooleanField(default=False)),
                ('github_link', models.TextField(blank=True)),
                ('picture', models.ImageField(default='default_work.png', upload_to='work_thumbnails')),
                ('previous_picture', models.TextField(blank=True)),
            ],
        ),
    ]
