# Generated by Django 4.1.5 on 2023-01-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_experience_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myintro',
            name='bio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='myintro',
            name='greeting_text',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='myintro',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='socialwebsite',
            name='site',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
