# Generated by Django 3.0.8 on 2021-01-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210106_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_text', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('minor', models.CharField(max_length=50)),
                ('micro_credential', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='my-pic.png', upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('previous_picture', models.TextField(blank=True)),
                ('resume_link', models.TextField(blank=True, default='#')),
            ],
            options={
                'verbose_name': 'My Intro',
                'verbose_name_plural': 'My Intros',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50)),
                ('classes', models.CharField(max_length=50)),
                ('link', models.TextField()),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('OS', 'Open Source'), ('PR', 'Project'), ('CB', 'Contribution')], default='PR', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.ImageField(default='default_project.png', upload_to='project_thumbnails'),
        ),
        migrations.AddField(
            model_name='project',
            name='previous_picture',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
