# Generated by Django 3.0.8 on 2021-01-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210107_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myintro',
            name='bio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='myintro',
            name='greeting_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='classes',
            field=models.TextField(),
        ),
    ]
