# Generated by Django 3.0.8 on 2021-01-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210108_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='on_github',
            field=models.BooleanField(default=False),
        ),
    ]
