# Generated by Django 3.0.8 on 2021-01-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_project_in_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myintro',
            name='major',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='myintro',
            name='micro_credential',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='myintro',
            name='minor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
