# Generated by Django 3.0.8 on 2021-01-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210108_0431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialLink',
            new_name='SocialWebsite',
        ),
    ]
