# Generated by Django 3.0.8 on 2021-01-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210108_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialwebsite',
            options={'verbose_name': 'Social Website', 'verbose_name_plural': 'Social Websites'},
        ),
    ]
