# Generated by Django 3.0.8 on 2021-01-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210108_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('OS', 'Open Source'), ('PR', 'Project'), ('CB', 'Contribution')], default='PR', max_length=2)),
                ('description', models.TextField(blank=True)),
                ('in_production', models.BooleanField(default=False)),
                ('production_link', models.TextField(blank=True)),
                ('on_github', models.BooleanField(default=False)),
                ('github_link', models.TextField(blank=True)),
                ('picture', models.ImageField(default='default_work.png', upload_to='work_thumbnails')),
                ('previous_picture', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterField(
            model_name='myintro',
            name='picture',
            field=models.ImageField(default='default-me-pic.png', upload_to=''),
        ),
    ]
