# Generated by Django 3.0.8 on 2021-01-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210108_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='def-favicon.ico', upload_to='')),
                ('previous_logo', models.TextField(blank=True)),
                ('intro', models.BooleanField(default=False)),
                ('intro_background', models.ImageField(default='def-intro-back.jpg', upload_to='backgrounds')),
                ('previous_intro_background', models.TextField(blank=True)),
                ('work', models.BooleanField(default=False)),
                ('work_background', models.ImageField(default='def-work-back.jpg', upload_to='backgrounds')),
                ('previous_work_background', models.TextField(blank=True)),
                ('experience', models.BooleanField(default=False)),
                ('experience_background', models.ImageField(default='def-experience-back.jpg', upload_to='backgrounds')),
                ('previous_experience_background', models.TextField(blank=True)),
                ('about', models.BooleanField(default=False)),
                ('about_background', models.ImageField(default='def-about-back.jpg', upload_to='backgrounds')),
                ('previous_about_background', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'HomePage',
                'verbose_name_plural': 'HomePages',
            },
        ),
    ]
