# Generated by Django 3.0.8 on 2021-01-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='experience',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='work',
            field=models.BooleanField(default=True),
        ),
    ]
