# Generated by Django 3.0.8 on 2021-01-16 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210115_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='in_development',
            new_name='show_status',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='development_message',
            new_name='status_message',
        ),
    ]
