# Generated by Django 3.0.8 on 2021-05-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210116_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('end_date', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('OS', 'Volunteer'), ('IS', 'Internship'), ('PT', 'Part Time'), ('FT', 'Full Time'), ('RS', 'Research')], default='IS', max_length=2)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
    ]
